spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop # SessionFactory 가 시작될 때 Drop, Create, Alter / 종료될 때 Drop
    properties:
      hibernate:
        format_sql: true
        show_sql:  true
jwt:
  header: Authorization
  # HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 함
  # Base64: meun-tech-spring-boot-jwt-tutorial-secret-meun-tech-spring-boot-jwt-tutorial-secret
  secret: bWV1bi10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtbWV1bi10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQ=
  token-validity-in-seconds: 86400
logging:
  level:
    com.study: DEBUG